### ISSUE TITLE
BarGauge 차트가 최근 확장행 값으로 덮어씌워짐 관련 test code 작성

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#195]
**개요 및 요청사항**
- BarGauge 차트가 최근 확장행 값으로 덮어씌워짐 관련 test code 작성

- BarGague 를 두개 만들어 하나의 scrop 값을 변경하면 다른 BarGague 에 반영 되면 안 된다

**결과물**
-BarGauge 차트가 최근 확장행 값으로 덮어씌워짐 관련 test code

**완료 기준**
- [ ]  PR Review @

**Comment by toyjhlee** [comment]
다음 Component 를 만들어 확인 한 결과
원인은 두개로 판단 됩니다.
1. TBody 내부의 tr 의 key 값이  1페이지와 2페이지가 같았다
2. 1번 조건 key 값이 같은 경우 style 값이 2 개 이상이면 Dom 을 업데이트 하지 않는 듯 하다

```
import React from 'react'
import BarGauge from '@Charts/BarGauge'

class MultiBarGage extends React.Component {
  render() {
    return <>
      <BarGauge score={this.props.score1 * 100}></BarGauge>
      <BarGauge score={this.props.score2 * 100}></BarGauge>
      <BarGauge score={0}></BarGauge>
    </>
  }
}

export default MultiBarGage
```

**Comment by toyjhlee** [comment]
styled-component 를 사용하거나
module.css 를 사용하면 발생하지 않을 듯 합니다
기존의 
```
const styles = {
  "gauge_container":{
    ...
  },
  "bar_gauge_fill":{
    ...
  }
}
```
은 사용하지 않아야 할 듯 합니다.

Close 하겠습니다

**Comment by toyjhlee** [comment]
[PR](ttps://github.com/linewalks/MDwalks-UI/compare/feature/issue.195)
