### ISSUE TITLE
요약카드 차트 폰트 크기, 가로선 간격 수정

### ISSUE THREAD

**Issue by hurcy** [linewalks/MDwalks-UI#228]
**개요 및 요청사항**
폰트 크기와 가로선 간격을 수정합니다.

**결과물**
- x,y축 폰트 크기 14로 변경
- high risk patient 요약카드의 가로선 간격 50

**완료 기준**
- [ ]  PR Review @

**Comment by jik0090** [comment]
@hurcy 가로간격은 Cardio에서 바꾸겠습니당.
