### ISSUE TITLE
Code clean 폴더 정리

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#272]
**개요 및 요청사항**

다음 리스트의 아래에서 사용하지 앟는 파일을 삭제 해주세요
- [ ] ./src/data 
- [ ]  ./src/assets/img

**결과물**
정상 동작해야 합니다

**완료 기준**
- [ ]  PR Review @

**Comment by jik0090** [comment]
@toyjhlee ./src/data는 신영님이 논문작성을 위해 필요할수도 있다고 하십니다. 저 폴더는 그대로 냅두고 진행해도될까요?

**Comment by toyjhlee** [comment]
> @toyjhlee ./src/data는 신영님이 논문작성을 위해 필요할수도 있다고 하십니다. 저 폴더는 그대로 냅두고 진행해도될까요?

넵
