### ISSUE TITLE
CDM BarChart를 MDwalks-UI로 Migration

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#369]
## 기능 요청이 문제와 연관이 있습니까? 설명해주세요
CDM BarChart를 MDwalks-UI로 Migration

## 원하는 솔루션에 대한 설명
Migration된 CDM BarChart 

## BarChart 관련 테스트 항목
- [x] BarChart 는 isEmpty 인 경우 EmptyPlaceHolder 보여지는지 확인
- [x] BarChart 는 isEmpty 가 아닌 경우 Rechart.BarChart 가 그려지는지 확인

## TooltipBox 관련 테스트 항목
- [ ]  showOrigin 인경우 value 값이 toFixed, toLocaleString 적용되지 않는다
- [ ]  isPercent 인 경우 toFixed 이 적용된다
- [ ]  isPercent, showOrigin 둘 다 지정하지 않는 경우 toLocaleString 이 적용된다

**Comment by SyngEiEi** [comment]
- TooltipBox
 - payload를 정상적으로 렌더
 - payload를 정상적으로 렌더(퍼센트)
 - payload를 정상적으로 렌더(지수형)
 - dataKey, nameKey 지정

**Comment by toyjhlee** [comment]
TooltipBox.js 에 아래 부분은 삭제 해주세요
`typeof value === 'string' && (value.indexOf('e') !== -1)`
