### ISSUE TITLE
TreeMap 을 rechart 로 만드는 것에 대한 검토

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#374]
## 기능 요청이 문제와 연관이 있습니까? 설명해주세요
TreeMap 을 rechart 로 변경 시 필요한 수정과 사이드 임팩트에 대한 
검토 해주시겠어요?

**Comment by jik0090** [comment]
https://jsfiddle.net/alidingling/u702a3Lx/

API문서에는 없지만, Treemap은 onClick property를 받을 수 있습니다. clcik했을 때, click event로 넘어오는 props는 다음과 같습니다.

![Screenshot from 2020-02-06 11-01-15](https://user-images.githubusercontent.com/37281455/73899532-4ec2ad00-48d0-11ea-9fb8-b4bad678ae76.png)

**Comment by toyjhlee** [comment]
네 감사합니다
