### ISSUE TITLE
RadarChart 을 rechart 로 만드는 것에 대한 검토

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#375]
## 기능 요청이 문제와 연관이 있습니까? 설명해주세요
RadarChart 을 rechart 로 변경 시 필요한 수정과 사이드 임팩트에 대한 
검토 해주시겠어요?

**Comment by jik0090** [comment]
![Screenshot from 2020-02-06 15-40-26](https://user-images.githubusercontent.com/37281455/73912128-184c5880-48f7-11ea-8fd9-faa078c6055f.png)

하이차트에서 쓰는 데이터 형태는 위의 그림과 같습니다.

![Screenshot from 2020-02-06 15-41-29](https://user-images.githubusercontent.com/37281455/73912178-331ecd00-48f7-11ea-8399-fd2f7239657e.png)

rechart에서 쓰는 데이터포맷은 위와 같습니다. 지금은 데이터를 컨버팅하는 함수 or 백엔드에서 데이터형태 변경이 필요합니다.

**Comment by toyjhlee** [comment]
색상 적용은 어떻게 할 수 있을까요?
jsfiddle 로 하나 만들어서 검토 해주시겠어요?

**Comment by jik0090** [comment]
> 색상 적용은 어떻게 할 수 있을까요?
> jsfiddle 로 하나 만들어서 검토 해주시겠어요?

stroke와 fill props를 이용해서 할 수 있습니다.

https://jsfiddle.net/jik0090/ey7npwLv/8/
