### ISSUE TITLE
TimeToEvent 을 rechart 로 만드는 것에 대한 검토

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#387]
## 기능 요청이 문제와 연관이 있습니까? 설명해주세요
TimeToEvent 을 rechart 로 변경 시 필요한 수정과 사이드 임팩트에 대한
검토 해주시겠어요?

**Comment by jik0090** [comment]
https://jsfiddle.net/jik0090/3jr2ah7b/3/

recharts의 scatter차트를 이용하여 변경할수 있으며, 기존 데이터 타입만 변경하는 convert함수 구현과 customShape를 통하여 처음 원과 마지막원의 다른컬러를 주는 구현이 필요해보입니다.
