### ISSUE TITLE
Histogram 을 rechart 로 만드는 것에 대한 검토

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#388]
## 기능 요청이 문제와 연관이 있습니까? 설명해주세요
Histogram 을 rechart 로 변경 시 필요한 수정과 사이드 임팩트에 대한
검토 해주시겠어요?

**Comment by jik0090** [comment]
* https://github.com/recharts/recharts/issues/1580
* https://jsfiddle.net/jashanbhullar/149e8gk5/

recharts로 histogram을 만드려면, d3를 이용하여 histogram데이터로 변경후, recharts로 렌더링하는 방식을 사용하고 있습니다. d3를 이용한 data변경 함수와 bins개수를 변경하는 eventhandler 구현이 필요해보입니다.

**Comment by toyjhlee** [comment]
d3 를 사용해서 histogram Data  변경과 bins 계수를 구함
