### ISSUE TITLE
Histogram 을 rechart 로 변경

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#394]
## 기능에 관한 설명 또는 링크
명확하고 간결한 설명

## 선행 이슈 링크
#388

## 원하는 솔루션에 대한 설명
BarChart 를 사용하고 Histogram Data  변경 로직은 구현한다

## 요구 조건
- [ ] 기존 TimeToEvent 에서 사용하는 property 를 따른다

**Comment by jik0090** [comment]
이 이슈는 rechart의 경우 히스토그램을 BarChart로 대체하라고 하고 있습니다. 하지만 히스토그램 차트는 바들이 x축 구간안에(예를 들어, 0~0.1사이) 바차트들이 렌더링되어야하는데, rechart의 BarChart의 경우 바들이 x축의 x좌표가 대응되기때문에 변경을 하지 않는게 좋을것 같습니다.
