### ISSUE TITLE
Tabs의 border-bottom을 hidden 하고 싶습니다

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#434]
## 기능에 관한 설명 또는 링크
MDwalks-UI의 Tabs를 사용하고 있습니다
Tabs의 기본으로 설정되어있는 border-bottom을 hidden 처리 할 수 있는 기능이 필요합니다

## 선행 이슈 링크
없습니다

## 원하는 솔루션에 대한 설명
Tabs 설정에서 border-bottom을 제어하는 기능을 추가해주십시오

## 요구 조건
- [ ] border-bottom 제어가 추가되어야 합니다

## 테스트 항목
- [ ] border-bottom hidden 시에 렌더링 되지 않아야 합니다

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
이건 닫겠습니다
