### ISSUE TITLE
v0.13.9 TextLink에 hover 시에도 basic의 색상 유지가 되지 않습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#452]
## 버그에 대한 설명
hover 시에 basic이면 basic의 색상 유지가 되어야 하는데, 
basic의 경우 hover 시에 primary 색상이 되어버리는 이슈가 있습니다.

## 재현
재현하는 단계
```
<a href={link} target="_blank" rel="noopener noreferrer">
  <TextLink hasIcon>
    <TextLink.Icon
       src="/static/svg/icn-link-xs.svg"
       alt="Atlas link button"
    />
       ATLAS
   </TextLink>
</a>
```
와 같은 형태로 작성하고 사용했을 경우 CDM-Client에서는 hover 시에 색상이 변경됩니다.

## 기대 행동
hover 시에도 basic으로 설정되면 색상이 변경되지 않았으면 좋겠습니다.

## 스크린샷
<img width="342" alt="스크린샷 2020-03-12 15 27 08" src="https://user-images.githubusercontent.com/9410300/76493436-f5710f00-6475-11ea-9564-cf9250ecf3ca.png">

## 환경
운영 체제: macOS
브라우져, 버전 : 버전 80.0.3987.122(공식 빌드) (64비트)
MDWalks-UI 버전 : v0.13.9

## 추가 설명
CDM-Client에서는 발생하지만 guide에서는 보이지 않는 것으로 보아 CDM-Client의 문제일 수도 있으니 문제를 파악하다 발견되면 바로 이슈에 댓글을 남기겠습니다.

**Comment by toyjhlee** [comment]
```
:hover { color 값 지정 }
```
