### ISSUE TITLE
Modal이 열리는 시점 내부에 focus를 제어하고 싶습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#455]
## 기능에 관한 설명 또는 링크
Modal을 사용할 때 실제 isOpen이 true가 되어야 내부의 컴포넌트들이 그려집니다.
그렇기에 호출하는 쪽에서는 focus를 주기 위해서는 
```
  useEffect(() => {
    if (isOpen) InputEl.current.focus()
  }, [isOpen])
```
와 같은 형태를 수행했습니다.
이 기능을 Modal에 props을 전달하는 것만으로도 사용할 수 있었으면 좋겠습니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
```
<Modal
  ...
  initFocusEl={selector}
  ... />
```
와 같은 형태가 필요합니다.

## 요구 조건
- [ ] Modal에 props을 활용하여 내부 element에 focus를 할 수 있도록 해주세요.

## 테스트 항목
- [ ] Modal Open시 특정 항목 focus 및 제어 테스트

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
autoFocusButton
autoFocusInput

**Comment by toyjhlee** [comment]
autoFocusInput 의 지원이 React 에서 추천하지 않는다고 하네요
https://ko.reactjs.org/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components

필요하다면 Modal 에서 Data 를 받아서 input 를 그려주는 방향으로 만들어야 합니다.
