### ISSUE TITLE
MDwalk-UI 차트를 사용할 때 차트내부 상단에 ReferenceLine을 넣고 싶습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#506]
## 기능에 관한 설명 또는 링크
MDwalk-UI 차트를 사용할 때 차트내부 상단에 ReferenceLine을 넣고 싶습니다.

<img width="1134" alt="스크린샷 2020-03-27 11 01 45" src="https://user-images.githubusercontent.com/9410300/77716204-f468e180-7020-11ea-87ec-df974550ed89.png">

위 이미지에서는 Yaxis 9,000 위에 `건`에 맞춰서 ReferenceLine이 형성되어 있습니다.
#505 과 연계되는 이슈인 것같습니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
Chart의 최상단에 ReferenceLine과 라벨이 동일선상에 존재했으면 좋겠습니다.

## 요구 조건
- [ ] Line이 무조건 그려지는 것은 아니고 선택을 할 수 있어야 합니다.

## 테스트 항목
- [ ] Line을 나타내는 element가 렌더링 되는 것을 테스트합니다.

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
@thiporia 아래 처럼 표현하면 안 되나요?
https://jsfiddle.net/toyjhlee/k3qg7vp4/1/

이유는 아래와 같습니다
1. 저렇게 되면 domain 을 저 line 을 위해 늘려야함
2. 그래프가 세로로 긴 경우 가독성이 떨어짐

**Comment by toyjhlee** [comment]
그리고 이건 티켓이 YAxis 에 label 추가 요청이 명확 할 거 같습니다.
line 을 넣는 건 디자인 구현 방법 중 하나로 생각 됩니다

**Comment by thiporia** [comment]
@toyjhlee 예 알겠습니다. 이슈는 닫도록 하겠습니다!
