### ISSUE TITLE
MDwalks-UI.Table의 scroll을 적용한 경우 column의 width가 head, body, foot을 서로 동일하게 사용하고 싶습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#512]
## 기능에 관한 설명 또는 링크
MDwalks-UI.Table의 scroll을 적용한 경우 column의 width가 head, body, foot을 서로 동일하게 사용하고 싶습니다.
현재는 아래 이미지와 같이 head, body, foot의 width가 서로 다른 경우가 있습니다.
세 군데에서 column을 동일하게 사용하고 싶습니다.
<img width="1236" alt="스크린샷 2020-03-31 17 05 30" src="https://user-images.githubusercontent.com/9410300/78002781-a894a000-7372-11ea-9cf8-844b57157f3c.png">

테이블 사용 간 테이블을 감싸고 있던 Wrapper style은 아래 코드와 같습니다.
기본적인 정렬과 색상 폰트 웨이트 커스텀을 진행하였습니다.
```
const Section = styled.section`
  td:first-child:not(:only-child), th:first-child {
    text-align: left;
  }
  td:not(:first-child), th:not(:first-child) {
    text-align: right;
  }

  td:last-child {
    color: ${variables.color.$solid_default}
  }

  tfoot {
    td {
      font-weight: bold;
    }
  }
`
```

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
Table에 scroll을 적용하는 경우, 
thead, tbody, tfoot의 column의 width가 일정해야합니다.

## 요구 조건
- [ ] thead, tbody, tfoot의 column의 width를 일정하게 가져가도록 해야합니다.

## 테스트 항목
- [ ] -

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
```
{
  width,
  align,
}
```

**Comment by toyjhlee** [comment]
@thiporia  
https://linewalks.github.io/MDwalks-UI/#table 에서 
scroll Array List 을 참고 하세요
