### ISSUE TITLE
MDwalks-UI.Table 사용 중에 행을 합친 경우 배경 색상이 번갈아서 표현이 되지 않습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#535]
## 버그에 대한 설명
MDwalks-UI.Table 사용 중에 행을 합친 경우 배경 색상이 번갈아서 표현이 되지 않습니다.
<img width="1166" alt="스크린샷 2020-04-14 10 55 22" src="https://user-images.githubusercontent.com/9410300/79177807-9fa9d100-7e3e-11ea-9627-6edff719124d.png">

위 이미지에서는 일부삭제, 일부교체, 전부교체의 색상이 흰색/그레이/흰색 순으로 보여져야하는데,
흰색/흰색/그레이 순으로 보여지고 있습니다.

## 재현
재현하는 단계
1. 아래 이미지를 참고합니다.
<img width="976" alt="스크린샷 2020-04-14 11 03 57" src="https://user-images.githubusercontent.com/9410300/79178232-a8e76d80-7e3f-11ea-84fa-90b78ee578c3.png">

## 기대 행동
행을 병합하였을 때 각각 cell의 배경색상의 교차가 독립적이었으면 좋겠습니다.

## 스크린샷
없습니다.

## 환경
운영 체제: macOS
브라우져, 버전: Chrome 80
MDWalks-UI 버전: v0.13.17

## 추가 설명
버그에 대한 추가적인 설명

**Comment by toyjhlee** [comment]
응급처치로 
```
[{rowSpan: 2, text: 'a2', className: 'odd'}, 'b4', 'c4'],
```
으로 하면 처리 됩니다.
className : 'odd', 'even'
