### ISSUE TITLE
Chart에 두가지 이상의 테마를 적용하고 싶습니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#537]
## 기능에 관한 설명 또는 링크
Chart에 두가지 이상의 테마를 적용하고 싶습니다.
그로 인해서 파생되는 범례에도 두 가지 이상의 색상이 반영되었으면 좋겠습니다.
<img width="929" alt="스크린샷 2020-04-14 17 45 03" src="https://user-images.githubusercontent.com/9410300/79204826-1e6f3000-7e78-11ea-9acf-469cdf81cfce.png">

위 이미지를 보시면 유지에 그린 테마, 변경에 골드 테마가 입혀져 있습니다.
또 추가적으로 Legend(범례)를 보시면 기존에 한 개의 점이 존재하였는데, 
두 가지 테마가 적용되면서 범례에도 두 가지 색상의 점이 존재하게 되었습니다.

따라서, 특수한 상황의 경우 테마가 두 가지 이상이 반영되어야 할 수있는 경우를 대응하고 싶습니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
Chart에 두 가지 이상의 테마를 적용하여, 사용하고 연관되어 범례에도 두 가지 이상의 테마가 그대로 적용되어야 합니다.

## 요구 조건
- [ ] 두 가지 이상의 테마 적용.

## 테스트 항목
- [ ] -

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
themes={[Themes.ThemeArrangePrimarySea, Themes.ThemeArrangeQuaternaryGold]}
