### ISSUE TITLE
BarChartMulti에 theme를 적용할 수 있는 방법이 필요합니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#544]
## 기능에 관한 설명 또는 링크
<img width="1174" alt="스크린샷 2020-04-21 18 18 09" src="https://user-images.githubusercontent.com/9410300/79848760-7966d100-83fc-11ea-9fce-11d7923df3f3.png">

BarChartMulti에 theme를 적용할 수 있는 방법이 필요합니다.
해당 이슈는 CDM 마일스톤 v1.2.0에 적용 예정입니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
BarChartMulti에 theme를 적용하고 싶습니다.

## 요구 조건
- [ ] 기존 ChartColor를 위 이미지와 같은 BarChart에도 theme로 적용할 수 있어야 합니다.

## 테스트 항목
- 없습니다.

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
하나의 color 인지
하나의 theme 인지
여려개의  theme 인지
를 말씀해주시겠어요?
