### ISSUE TITLE
font.TextOverflow를 두 줄 이상의 경우에도 적용할 수 있도록 요청드립니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#548]
## 기능에 관한 설명 또는 링크
font.TextOverflow를 2줄 이상의 경우에도 적용할 수 있는 방안을 요청드립니다.

## 선행 이슈 링크
[zeplin](https://zpl.io/bzoyOZl)

## 요구 조건
- [ ] font.TextOverflow가 두 줄 이상의 경우에도 `...`을 노출해야합니다.

## 테스트 항목
- 없습니다

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
IE 에서 지원이 필요할 시 다음 lib [react-lines-ellipsis](https://github.com/xiaody/react-lines-ellipsis#readme) 사용
