### ISSUE TITLE
Table Data 형식 추가

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#549]
## 기능에 관한 설명 또는 링크
```
['기능', ['1', '2', '3']]
```
이 ->
```
[
  { rowSpan: 3, text: '기능' }
  '1', '2', '3',
]
```
으로 변환해서 처리

## 선행 이슈 링크
없음

## 원하는 솔루션에 대한 설명
로직으로 처리

## 요구 조건
- [ ] 위 기능을 만족

## 테스트 항목
- [ ] 기능 조건을 만족하는 함수 테스트
- [ ] 

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
참고 : https://yona.linewalks.com/MDwalks_for_CDM/CDM-Client/pullRequest/227/changes

**Comment by thiporia** [comment]
MDwalks-UI 를 더이상 업데이트 하지 않으므로 해당 이슈를 닫습니다.

**Comment by toyjhlee** [comment]
> MDwalks-UI 를 더이상 업데이트 하지 않으므로 해당 이슈를 닫습니다.

넵
