### ISSUE TITLE
SummaryCard에서 events가 있으면 hover효과 테스트코드 추가

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#574]
## 기능에 관한 설명 또는 링크
- SummaryCard에서 events가 있으면 hover효과

## 선행 이슈 링크
- 없음

## 원하는 솔루션에 대한 설명
명확하고 간결한 설명

## 요구 조건
- [x] SummaryCard에서 events가 있으면 hover효과 테스트코드 추가

## 테스트 항목
- [x] events가 있는 SummaryCard는 css hover를 가지고 있어야 한다.

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
다음을 참조 : https://github.com/linewalks/MDwalks-UI/wiki/TEST-styled-components
