### ISSUE TITLE
Chart 에 React Context 사용

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#599]
## 기능에 관한 설명 또는 링크
`context를 이용하면 단계마다 일일이 props를 넘겨주지 않고도 컴포넌트 트리 전체에 데이터를 제공할 수 있습니다.` [React Context](https://ko.reactjs.org/docs/context.html)

## 선행 이슈 링크
없음

## 원하는 솔루션에 대한 설명
textMap, isPercent 을 Context 로 처리

## 요구 조건
- [ ] BarChart적용
- [ ] BarChartMuli 적용
- [ ] LineChart 적용
- [ ] PieChart 적용

## 테스트 항목
- [ ] 관련 테스트 항목 추가

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
지금 생각해보면 사용하지 않아도 될 듯 합니다.
이 이슈를 닫는 조건
  - 지금 상황에 맞지 않는다고 판단 되는 경우
  - 다음 기능을 만족하는 다른 방법 적용 `단계마다 일일이 props를 넘겨주지 않고도`

@jik0090 @thiporia

**Comment by thiporia** [comment]
context를 굳이 사용하지 않아도 좋을 것 같습니다.

**Comment by toyjhlee** [comment]
> context를 굳이 사용하지 않아도 좋을 것 같습니다.

네 그럼 `Close` 할 까요?
