### ISSUE TITLE
CheckList를 가로 방향으로 나열하는 기능을 요청드립니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#614]
## 기능에 관한 설명 또는 링크
CheckList를 가로 방향으로 나열하는 기능을 요청드립니다.
<img width="953" alt="스크린샷 2020-05-25 10 54 14" src="https://user-images.githubusercontent.com/9410300/82771178-18587000-9e76-11ea-9587-8fd5a7502aa7.png">

위 이미지와 같은 형태의 컴포넌트가 concept search 페이지의 검색 조건 필터링 적용에 필요합니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
현재의 CheckList를 가로로 표현할 수 있는 컴포넌트가 필요합니다.

## 요구 조건
- [ ] CheckBox가 가로로 나열될 수 있어야 합니다.

## 테스트 항목
- [ ] 그려지는 컴포넌트의 CheckBox들이 가로로 나열됩니다.

## 완료 후 진행
- [ ] Item: color, disabled 시 color 문의 to UX
PR 을 신청합니다

**Comment by toyjhlee** [comment]
다음은 어디에 들어 가야 할 까 
```
export const LAYOUT = {
  HORIZONTAL: 'horizontal',
  VERTICAL: 'vertical',
  TEST: 'vertical1',
}
```

**Comment by toyjhlee** [comment]
horizontal 인 경우
`padding-left: 0`
