### ISSUE TITLE
두 개의 Chart 가 하나의 범례를 공통으로 사용하는 기능이 필요합니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#617]
## 기능에 관한 설명 또는 링크
<img width="1254" alt="스크린샷 2020-05-25 19 21 54" src="https://user-images.githubusercontent.com/9410300/82804310-05b55980-9ebd-11ea-9bf3-26af086dc820.png">

위 이미지와 같이 두 개의 차트가 하나의 범례를 공통으로 지니는 기능이 필요합니다.
*특이사항 : 위 이미지에서는 우측 차트는 색상이 입혀지지 않은 상태입니다.
보통은 아래 차트와 같이 같은 범례와 ColorSet을 지니고 있습니다.(위 이미지는 범례의 width 영역을 보여드리기 위함입니다.)
<img width="1277" alt="스크린샷 2020-05-25 19 28 16" src="https://user-images.githubusercontent.com/9410300/82804795-e66afc00-9ebd-11ea-9278-135c3932395f.png">

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
차트를 두 개 생성 하였을 경우에, 하나의 범례를 공통으로 가질 수 있는 기능이 필요합니다.

## 요구 조건
- [ ] 그려지는 차트가 2개, 범례는 하나만 그려져야 합니다.
- [ ] 범례는 두 개의 차트를 합친 영역 만큼의 width 를 지닐 수 있습니다.

## 테스트 항목
- [ ] 그려지는 차트가 2개인 경우에 그려지는 범례가 하나인지 확인합니다.

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
- [ ] LegendList 수정
- [ ] LegendList 그리지 않는 property 제공
