### ISSUE TITLE
PieChart 의 colorList 삭제

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#618]
## 기능에 관한 설명 또는 링크
Theme 로 제어하게 합니다

## 선행 이슈 링크
없음

## 원하는 솔루션에 대한 설명
PieChart 의 colorList 삭제

## 요구 조건
- [ ] PieChart 의 colorList 삭제

## 테스트 항목
- [ ] 없음

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
@thiporia 다음 버전으로 이동 할 게요
이유는 아래 두가지의 물음 때문 입니다.

1. CDM 수정 되었나요?
2. 아니면 MDwalks-UI 적용 후 문제 있는 부분을 삭제 할 껀가요?

**Comment by thiporia** [comment]
@toyjhlee 님 늦게 확인하여 정말 죄송합니다.
1. CDM은 아직 colorList를 사용하고 있습니다.
2. MDwalks-UI에 적용이 되면 해당 부분을 theme로 대체할 예정입니다.
대체 theme는 영지님께 문의 후 해당 부분 디자인 시안 업데이트 및 페이지 반영 할 생각입니다.

**Comment by toyjhlee** [comment]
@thiporia 삭제 가능하게 되면 코멘트 남겨 주세요

**Comment by thiporia** [comment]
@toyjhlee 님 삭제 가능합니다.  : )

**Comment by toyjhlee** [comment]
> @toyjhlee 님 삭제 가능합니다. : )

넵 고마워요
