### ISSUE TITLE
ChartColor 에 Theme 추가

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#620]
## 기능에 관한 설명 또는 링크
[시안](https://zpl.io/V47DQ1p)

## 선행 이슈 링크
없음

## 원하는 솔루션에 대한 설명
없음

## 요구 조건
- [ ] ThemeComparePrimarySea 에 추가

## 테스트 항목
- [ ] ChartColor.test.js 에 추가

## 완료 후 진행
PR 을 신청합니다

**Comment by youngji-k** [comment]
범례 컬러 11개 중에 `#gold500` 을 `#sea500` 으로 수정 부탁드립니다.

**Comment by toyjhlee** [comment]
@youngji-k 이슈를 만드세요 ㅎㅎㅎ
