### ISSUE TITLE
LegendList에 Chart와 같은 스타일의 colorSet을 적용하는 기능을 요청합니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#638]
## 기능에 관한 설명 또는 링크
현재 Chart에서 legend={{ hide: true }} 를 적용하는 경우 Chart의 LegendList가 노출되지 않습니다.
기존에는 Chart와 LegendList가 동일한 ChartColor를 적용받지만, 
이 경우(legend가 hiding) 기존과는 다르게 차트에 적용된 ChartColor를 적용하는 기능이 없으므로
(하나하나 색상을 넣어줄 순 있지만, MDwalks-UI의 ChartColor 변화를 동적으로 반영하기 힘듭니다.)
LegendList에도 ChartColor를 적용하는 기능이 필요해졌습니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
LegendList에도 ChartColor(theme)를 적용할 수 있어야 합니다.

## 요구 조건
- [ ] LegendList에 ChartColor 적용.

## 테스트 항목
- [ ] 그려지는 범례가 적용한 ChartColor를 정확하게 반영하는지 확인.

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
@toyjhlee 님 이슈에 대한 검토 부탁드립니다.

**Comment by thiporia** [comment]
아래와 같은 형태로 작업을 할 수도 있을 것 같습니다.
```
const agesColorSet = ChartColor.getColorsByTheme(ChartColor.Themes.ThemeComparePrimarySea, 11)
```
다만, Theme를 적용하게는 좀 더 명확할 것 같습니다.

**Comment by thiporia** [comment]
```
<LegendList
  ...
  data={[{ color: 'red', text: 'a' }, { color: 'blue', text: 'b' }]}
  theme="compare"
  themes={[ theme1, theme2 ]}
/>
```

* 위와 같은 경우 color가 우선순위를 가질 것인가 아니면 theme가 우선순위를 지닐 것인가?
* color 속성을 제거하고 text만 입력 받을 것인가?
* 또한 theme가 멀티로 적용된 사례는 어떻게 반영할 것인가?

*(해당 컴포넌트를 사용하는 곳은 20.06.18 기준 CDM-Client에서만 사용 중.)*

**Comment by toyjhlee** [comment]
> ```
> <LegendList
>   ...
>   data={[{ color: 'red', text: 'a' }, { color: 'blue', text: 'b' }]}
>   theme="compare"
>   themes={[ theme1, theme2 ]}
> />
> ```
> 
> * 위와 같은 경우 color가 우선순위를 가질 것인가 아니면 theme가 우선순위를 지닐 것인가?
> * color 속성을 제거하고 text만 입력 받을 것인가?
> * 또한 theme가 멀티로 적용된 사례는 어떻게 반영할 것인가?
> 
> _(해당 컴포넌트를 사용하는 곳은 20.06.18 기준 CDM-Client에서만 사용 중.)_

color 가 우선순위를 가지는 것이 좋을듯 합니다

**Comment by toyjhlee** [comment]
진행해보세요 ㅎㅎㅎ
  - 검토 요청 확인이 늦어서 죄송합니다
