### ISSUE TITLE
[Table] Table UI 개선 - size 및 color 적용

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#649]
## 기능에 관한 설명 또는 링크
[zeplin](https://zpl.io/2Z7QkYE)
을 참고하여 Table의 style 중 size와 color를 재정의 합니다.
(size는 font-size, color, padding을 포함합니다.)

### 이슈 특이사항
`병합된 테이블의 hover`, `Row Header Table`는 해당 이슈의 처리 대상이 아닙니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
제플린과 동일한 형태의 style이 MDwalks-UI.Table에 적용됩니다.

### basic
- [x] 기본형태는 S(mall) / M(edium)으로 두 가지의 사이즈를 지닙니다.
~- [ ] 테이블이 스크롤을 지닐 경우 아래의 조건을 만족합니다.~
```
< 내부 스크롤 영역 height 기준  >
데이터 텍스트가 1줄일 때의 row 10.5개 기준 사용처에서 scroll.y에 값을 설정하는 것이 바람직
table s - height : 388px  /  table m - height : 514px
```
*값은 s/m 순으로 표기, 하나로 표기된 값은 둘 다 동일*
### thead
- [x] background는 grey02를 지닙니다.
- [x]  th, td는 아래와 같은 값을 지닙니다.
`size: 13/14, padding: 8px 16px/12px 24px, color: grey08, bold`
- [x] th의 처음과 마지막 자식요소의 border-radius가 기존 10px -> 8px로 변경
- [x] thead의 border-bottom이 `2px solid color.$line_dashboard_edge_grey` -> 
`1px solid colorV1.$grey04`로 변경되야 합니다.

### tbody
- [x] td는 아래와 같은 값을 지닙니다.(s/m 순으로 표기, 하나로 표기된 값은 둘 다 동일)
`size: 14/16, padding: 8px 16px/12px 24px, color: grey10`
- [x] `zebra pattern` 제거 대신 hover 시 `background: grey01`적용
- [x] tr은 첫번째 자식요소를 제외하고는 `border-bottom: 1px solid #grey04`를 적용
- [x] rowSpan 대상은 `.td[rowSpan] { border-right: 1px solid ${colorV1.$grey04}; }`을 적용

### tfoot
- [x] td는 아래와 같은 값을 지닙니다.(s/m 순으로 표기, 하나로 표기된 값은 둘 다 동일)
`size: 14/16, padding: 12px 16px/16px 24px, color: grey10, bold`
- [x] tr은 첫번째 자식요소를 제외하고는 `border-top: 1px solid ${colorV1.$grey04};`가 적용
- [x] tr의 첫번째 자식요소는 `border-top: 1px solid ${colorV1.$grey06};` 가 적용.
(tbody와의 구분을 위해서 색상이 더 진함)

## 테스트 항목
- [x] styleguidist에 그려진 항목을 확인합니다.

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요.
