### ISSUE TITLE
[Table] subHeader와 Size="medium"인 경우 subHeader.td와 tbody.td의 좌우패딩 불일치 문제 수정

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#657]
## 버그에 대한 설명
Table에서 subHeader를 적용할 경우 subHeader의 좌우 패딩이 16px임에도 불구하고,
Size가 'medium'인 경우 td의 좌우패딩이 24px으로 패딩이 불일치함으로 발생한 아래 이미지와 같은 문제를 수정합니다.(아래 이미지의 경우는 정렬이 우측으로 되어있는 경우입니다.)
<img width="729" alt="스크린샷 2020-06-16 18 40 39" src="https://user-images.githubusercontent.com/9410300/84866554-d3aaa800-b0b4-11ea-8bef-1bee7c8fd215.png">

## 재현
재현하는 단계
1. 재현을 위 이미지로 대체합니다.

## 기대 행동
subHeader도 기존의 16px로 고정이 아닌
size가 small인 경우 16px, medium인 경우 24px로 변경합니다.

## 스크린샷
없습니다.

## 환경
운영 체제: macOS
브라우져, 버전: Chrome 80
MDWalks-UI 버전: v0.13.31

## 추가 설명
없습니다.

**Comment by toyjhlee** [comment]
이게 변경 되면 table 스타일 적용을 일 부분 하겠네요

**Comment by thiporia** [comment]
테이블 스타일의 Size는 최대한 공통화 시킬 수 있을 것 같습니다.
