### ISSUE TITLE
RadioBox가 두 줄 이상인 경우 줄간격이 디자인 가이드라인과 다릅니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#671]
## 버그에 대한 설명

RadioBox의 리스트 내용이 두 줄 이상이 되었을 경우 디자인 가이드라인과 다른 문제 
<img width="869" alt="스크린샷 2020-06-25 10 27 03" src="https://user-images.githubusercontent.com/9410300/85643483-3ad8e580-b6cf-11ea-8835-5e55ab686fe9.png">
<-- 개발 버전 -->

<img width="880" alt="스크린샷 2020-06-25 10 33 43" src="https://user-images.githubusercontent.com/9410300/85643517-5c39d180-b6cf-11ea-84be-7a273e2a99e9.png">
<-- 디자인 시안 -->

## 재현
이미지로 대체합니다.

## 기대 행동
2줄 이상이 적용 될 경우 아이템의 줄간격을 24px을 가진다.

## 스크린샷
없습니다.

## 환경
운영 체제: macOS
브라우져, 버전: Chrome 80
MDWalks-UI 버전: MDwalks-UI v.0.13.32

## 추가 설명
없습니다.

**Comment by thiporia** [comment]
각 줄마다 지닐 수 있는 Box 개수를 고정하여 일정한 형태로 그려지게 하는 방법.
<img width="1148" alt="스크린샷 2020-06-25 10 41 07" src="https://user-images.githubusercontent.com/9410300/85643896-6f996c80-b6d0-11ea-88df-f5099e9bcbcc.png">

예를 들면 위와 같은 방식으로 그렇다면 사용자에게 노출하고 싶은 개수를 입력받게 하여 노출을 하는 것은 어떨까?
(name의 길이는 매우 유동적이기 때문)

**Comment by toyjhlee** [comment]
```
<box>
  <checkbox>
</box>
```

```
box {
  margin-bottom: -24px;
}
checkbox {
  margin-bottom: 24px
}
```

**Comment by toyjhlee** [comment]
checkbox 가 마지막 줄인지 css  만으로 알 수 없습니다.

**Comment by toyjhlee** [comment]
> 각 줄마다 지닐 수 있는 Box 개수를 고정하여 일정한 형태로 그려지게 하는 방법.
> <img alt="스크린샷 2020-06-25 10 41 07" width="1148" src="https://user-images.githubusercontent.com/9410300/85643896-6f996c80-b6d0-11ea-88df-f5099e9bcbcc.png">
> 
> 예를 들면 위와 같은 방식으로 그렇다면 사용자에게 노출하고 싶은 개수를 입력받게 하여 노출을 하는 것은 어떨까?
> (name의 길이는 매우 유동적이기 때문)

`이렇게 제한하여 해결하는 방법` 접근 시도가 좋았어요

**Comment by thiporia** [comment]
@toyjhlee 님 검토감사합니다. : )
말씀해주신대로 마지막 줄인지 알 수 있는 방법이 없다는 것을 생각하였습니다.
요한님의 검토를 바탕으로 아래와 같은 제약사항을 1차적으로 도출하였습니다.
1. `name`의 길이를 완전 범용으로 정할 수는 없다.(문자열 길이로 width를 고정할 수 없다.)
2. 현재 가장 중점적으로 사용하고 있는 CDM 기준 `ABCDE`로 정의해보자.(약 width: 100px)
3. 사용자에게 최대 개수 입력은 받지 않고, 너무 긴 name의 경우는 말줄임표(ellipsis)가 적용되는 것을 활용하자.

100px으로 가정할 경우 다음과 같습니다.
<img width="919" alt="스크린샷 2020-06-25 11 01 58" src="https://user-images.githubusercontent.com/9410300/85659223-43411880-b6ef-11ea-835e-5e050a407d38.png">

**Comment by toyjhlee** [comment]
> ```
> <box>
>   <checkbox>
> </box>
> ```
> 
> ```
> box {
>   margin-bottom: -24px;
> }
> checkbox {
>   margin-bottom: 24px
> }
> ```

@thiporia 이 방법은 검토 해봤나요?

**Comment by thiporia** [comment]
먼저 위에 작성해주신 방법은 아직 사용해보지 못했습니다.
저는 `구현을 어떻게 할 경우 가장 많은 데이터를 무리없이 뿌릴 수 있을까`와 `최소한의 props로 처리`하는 것에 중점을 두었습니다.
프로토타입 작업을 해본 결과 이미지는 아래와 같습니다.
<img width="948" alt="스크린샷 2020-06-26 16 31 24" src="https://user-images.githubusercontent.com/9410300/85832145-7efce080-b7ca-11ea-9847-1d81a04caa19.png">

프로토 타입 구현 순서
1. 모든 RadioBox의 각각의 Box는 name을 지닙니다. 예를 들면 `RadioBox_0`와 같은 값입니다.
2. useState에서 bottomBoxes의 여부를 지닌 배열을 가지고 있습니다.
3. 해당 배열에서 bottomBox로 체크된 Box들은 `className={bottomBox[idx] && "bottomBox"}`와 같은 형태로 class를 적용받게 됩니다.
4. bottomBox를 판별할 수 있는 기준은 아래 코드를 첨부합니다.
프로토타입이므로 동작하는 것을 기준으로 작성한 코드입니다.
```
// rbId라는 고유한 값을 props으로 전달받아야 합니다.
// 각 RadioBox간의 유니크함을 보장하여 document.getElementsByName이 특정 RadioBox만을 감지하도록 하기 위해서입니다.
const rePaintBox = () => {
    // rbId 는 props에서 전달받은 값입니다.
    const items = document.getElementsByName(`RadioBox_${rbId}`)
    let basisOffsetY = 0
    let maxDiffOffsetY = 0
    let bottomBoxIndexList = {}

    _.each(items, ({ offsetTop }, idx) => {
      if (idx === 0) {
        basisOffsetY = offsetTop
        bottomBoxIndexList[idx] = true
      } else {
        const diffOffsetY = offsetTop - basisOffsetY
        if (maxDiffOffsetY < diffOffsetY) {
          maxDiffOffsetY = diffOffsetY
          bottomBoxIndexList = {}
          bottomBoxIndexList[idx] = true
        } else if (maxDiffOffsetY === diffOffsetY) {
          bottomBoxIndexList[idx] = true
        }
      }
    })

    const { bottomBoxes } = this.state
    const newBottomBoxes = _.map(bottomBoxes, (isBottomBox, idx) => {
      if (_.indexOf(_.keys(bottomBoxIndexList), String(idx)) !== -1) return true
      return false
    })
    setBottomBoxes(newBottomBoxes)
  }
```

제가 생각한 원리는 다음과 같습니다.
1. 맨 처음에 그려진 박스(즉 위 이미지에서는 첫번째 박스인 'name 1')의 offsetTop을 먼저 파악하고 그 높이를 basisOffsetY로 잡습니다.
2. 해당 offsetTop을 기준으로 그려진 모든 box의 offsetTop을 basisOffsetY의 차를 구하여 maxDiffOffsetY를 갱신해나갑니다.
3. maxDiffOffsetY가 갱신 될 때마다 bottomBoxIndexList에는 maxDiffOffsetY와 값이 같거나 큰 diffOffsetY를 가진 경우 push해서 밀어넣습니다.
4. render가 될 때 해당 bottomBoxes에 포함된 index를 가진 경우 className에 `bottomBox`가 포함되고 해당 값들은 margin-bottm을 가지지 않도록 합니다.
```
  .bottomBox {
    margin-bottom: 0px !important;
  }
```

**Comment by thiporia** [comment]
@toyjhlee 님 말씀해주신 방법으로 적용하여 보았는데, 기존과 똑같은 형태로 보입니다.

**Comment by toyjhlee** [comment]
`dom` `cssom` 의 조합이란 가까워 지고 싶지만 가까워 지지 않는 대상같습니다.

제가 말한 방법이 안 되는 경우가 있을 수도 있습니다.
안 되는게 중요한게 아니라 제가 왜 그렇게 이야기 했는지가 중요합니다.

다행이 이건 보여드릴 수 있네요.
<img width="1440" alt="671" src="https://user-images.githubusercontent.com/366932/85961380-02921980-b9e5-11ea-8f3c-8a197f650f7e.png">

**Comment by jik0090** [comment]
@toyjhlee 이렇게 신경써주시는것만으로도 감사드립니당.

**Comment by thiporia** [comment]
@toyjhlee 님 이미지를 제공해주셔서 감사합니다. 
말씀해주신 방법으로 작업을 해보았습니다.

<img width="969" alt="스크린샷 2020-06-30 10 58 29" src="https://user-images.githubusercontent.com/9410300/86074838-a94be800-bac1-11ea-9b90-e8be83653773.png">

<img width="945" alt="스크린샷 2020-06-30 10 58 36" src="https://user-images.githubusercontent.com/9410300/86074831-a6e98e00-bac1-11ea-9699-95b79bed1127.png">

감싸고 있는 div의 영역을 기준으로 내부의 영역을 무시하고 다른 element들과 영역이 계산 되는 것을 확인하였습니다.
이것이 되는 연유가 외부에 있는 div box가 내부에 있는 div의 margin은 무시하는 것으로 이해를 하였습니다. 
padding의 경우였다면 자연스럽게 box의 영역으로 확보되어 위와 같은 현상으로 동작하지 않고 외부 div가 24px의 추가 bottom 영역을 가지는 것을 확인하였습니다.

https://codesandbox.io/s/div-yeongyeog-teseuteu-m28pr?file=/src/index.js

위 코드샌드박스에서 비슷한 현상을 테스트 해보았습니다.
