### ISSUE TITLE
PropTypes Warning 제거

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#702]
## 버그에 대한 설명
- LegendList와 TimeToEvent의 PropTypes 에러가 납니다.
## 재현
재현하는 단계
1. EXI의 모델 상세페이지 접속(LegendList),EXI의 환자 비교페이지 접속(TimeToEvent)
2. 개발자 도구 확인
3. 오류를 확인

## 기대 행동
- PropTypes 변경

## 스크린샷
![Screenshot from 2020-07-30 17-19-21](https://user-images.githubusercontent.com/37281455/88899425-fe2d7a80-d288-11ea-99b8-321eb2f5f784.png)
![Screenshot from 2020-07-30 17-18-59](https://user-images.githubusercontent.com/37281455/88899429-fff73e00-d288-11ea-985c-05ede912b068.png)

## 환경
운영 체제: [e.g. macOS]
브라우져, 버전 [e.g. Chrome 74]
MDWalks-UI 버전 [e.g. 1.0.0-beta.8]

## 추가 설명
버그에 대한 추가적인 설명

**Comment by thiporia** [comment]
@jik0090 님 확인하였습니다. LegendList에서도 나는군요. 이슈진행요청드립니다.
