### ISSUE TITLE
CheckList가 내부에 state를 지니지 않고, prop에 의해 제어되도록 수정합니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#705]
## 기능에 관한 설명 또는 링크
CheckList의 Ref를 통한 접근으로 내부 함수를 호출하는 의존성을 제거하고,
Parent Component에서 해당 컴포넌트의 상태를 관리하도록 수정합니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
- CheckList의 렌더링 상태는 props에 따라 정의됩니다.
- CheckList의 onChange 이벤트는 props.onChange를 호출합니다.

## 요구 조건
- [x] 내부 함수를 Ref를 통해 호출할 수 없어야 합니다.
- [x] CheckList의 상태는 Props를 통해서만 변경되어야 합니다.
- [x] 내부의 State가 존재해서는 안됩니다.(Stateless component가 되어야 합니다.)

## 테스트 항목
- [x] 기존 테스트 통과(내부 함수 테스트는 제거됩니다.)

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세영
