### ISSUE TITLE
Chart의 theme propTypes에 누락 된 테마 추가.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#725]
## 기능에 관한 설명 또는 링크
<img width="1731" alt="스크린샷 2020-08-20 16 47 17" src="https://user-images.githubusercontent.com/9410300/90731604-d8821700-e304-11ea-9424-d41239ad312b.png">

위 경고의 경우 propTypes에 누락된 값으로 생각됩니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
propTypes에 해당 ChartColor에 있는 값들을 추가하여 줍니다.

## 요구 조건
- [x] propTypes에 ChartColor를 추가합니다.
- [x] 경고가 뜨지 않아야 합니다.

## 테스트 항목
- [x] 기존 테스트 통과

## 완료 후 진행
PR 을 신청합니다

**Comment by Ian-90** [comment]
진행해주세요
