### ISSUE TITLE
파이차트 스타일가이드 적용

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#726]
## 기능에 관한 설명 또는 링크
- [시안](https://zpl.io/2EMlAly)
- 파이차트의 스타일 가이드를 적용합니다

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
- 시안에 맞는 스타일 가이드 적용

## 요구 조건
- [x] pie chart 사이즈 조정
- [x] 범례 배치

## 테스트 항목
- [x] 없음

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
진행요청드립니다.
