### ISSUE TITLE
타입스크립트 설정

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#727]
## 기능에 관한 설명 또는 링크
타입스크립트 코드작성을 위해 config 추가

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
tsconfig 추가

## 요구 조건
- [ ] 타입스크립트 설치
- [ ] tsconfig 추가

## 테스트 항목
- [ ] 없음

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
후 시작되는군요. 진행요청드립니다.
