### ISSUE TITLE
BarGauge 임계치 선 추가

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#739]
## 기능에 관한 설명 또는 링크
- [시안](https://app.zeplin.io/project/5cde6a28c2475c1e2be7ed26/screen/5f50d3dc5594a1494014139a)
- 시안에 맞는 임계치 선 추가

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
- threshold props가 있으면 position absolute로 위치를 이동시킵니다.

## 요구 조건
- [ ] 임계치 선 추가

## 테스트 항목
- [ ] threshold props가 있으면, 선이 추가되어야 합니다.

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
진행요청드립니다.
