### ISSUE TITLE
[eslint] Unexpected unnamed function 경고 제거

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#750]
## 기능에 관한 설명 또는 링크
[eslint] Unexpected unnamed function 경고 제거

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
경고 사라짐

## 요구 조건
- [x] 각 함수에 이름 정의

## 테스트 항목
- [x] 기존 동작 수행

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요
