### ISSUE TITLE
lineMergedTimeline 오타 수정

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#752]
## 버그에 대한 설명
- lineMergedTimeline y축라벨 수정
- [common](https://yona.linewalks.com/MDwalks_for_CDM/EXI-Common/issue/192)
- [시안](https://zpl.io/bWjwyee)

## 재현
재현하는 단계
1. ... 를 클릭하다
2. 스크롤를 내려라
3. 오류를 확인하라

## 기대 행동
- lineMergedTimeline y축라벨 Risk per visiting을 Risk Score per visiting으로 수정

## 스크린샷
문제해결을 위한 스크린샷이 있다면 추가

## 환경
운영 체제: [e.g. macOS]
브라우져, 버전 [e.g. Chrome 74]
MDWalks-UI 버전 [e.g. 1.0.0-beta.8]

## 추가 설명
버그에 대한 추가적인 설명

**Comment by thiporia** [comment]
진행요청드립니다.
