### ISSUE TITLE
버튼 스타일가이드 미적용 해결

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#756]
## 버그에 대한 설명
- 가이드 시안과 primary_light의 적용된 시안이 다릅니다.
- [가이드 시안](https://app.zeplin.io/project/5e38faee95bba5b3d116b616/screen/5d8b1a7c887f35619e9a9418)

## 재현
재현하는 단계
1. ... 를 클릭하다
2. 스크롤를 내려라
3. 오류를 확인하라

## 기대 행동
시안에 맞도록 BtnColor style 변경 및 관련코드 수정
 
## 스크린샷
![Screenshot from 2020-09-18 11-48-33](https://user-images.githubusercontent.com/37281455/93550313-188cf600-f9a6-11ea-93de-0a670fc948fd.png)

## 환경
운영 체제: [e.g. macOS]
브라우져, 버전 [e.g. Chrome 74]
MDWalks-UI 버전 [e.g. 1.0.0-beta.8]

## 추가 설명
버그에 대한 추가적인 설명

**Comment by thiporia** [comment]
진행요청드립니다.
