### ISSUE TITLE
Bar Chart X축 라벨 짤림현상

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#757]
## 버그에 대한 설명
x축 라벨이 g,p 글자를 포함하면, g와 p가 짤립니다. 

## 재현
재현하는 단계
1. ... 를 클릭하다
2. 스크롤를 내려라
3. 오류를 확인하라

## 기대 행동
기대 행동에대한 명확하고 간결한 설명

## 스크린샷
문제해결을 위한 스크린샷이 있다면 추가

## 환경
운영 체제: [e.g. macOS]
브라우져, 버전 [e.g. Chrome 74]
MDWalks-UI 버전 [e.g. 1.0.0-beta.8]

## 추가 설명
버그에 대한 추가적인 설명

**Comment by thiporia** [comment]
진행요청드립니다. :)

**Comment by jik0090** [comment]
해당 프로젝트 margin props로 해결하였습니다.
