### ISSUE TITLE
Table defaultSort 추가

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#770]
## 기능에 관한 설명 또는 링크
-Table defaultSort 추가

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
- defaultSort props를 추가하여, 기본 소팅 설정을 가능하게 합니다.
- sortOrder를 props로 받아서 sorting 순서를 제어 하도록 합니다.
  - 순서제어는 index로 반복해서 구현.

## 요구 조건
- [ ] defaultSort props를 추가
- [ ] sortOrder props를 추가

## 테스트 항목
- [ ] 그려지는 text 의 값이 21,223 가 되어야 한다
- [ ] Click 시 popup 이 나와야 한다

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
진향요청드립니다
