### ISSUE TITLE
color 정리

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#779]
## 기능에 관한 설명 또는 링크
사용하지 않는 예전컬러 제거 및 현재 컬러 적용

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
color와 colorV1 통합

## 요구 조건
- [x] ButtonLink
- [x] ButtonTextLink
- [x] ToggleLargeButton
- [x] SankeyChart
- [x] Footer
- [x] Navbar
- [x] list/item
- [x] modal
- [x] TooltipBox

## 테스트 항목
- [ ] 없음

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
진행요청드립니다.
