### ISSUE TITLE
[Modal] 모달의 형태를 시안에 맞도록 변경해야합니다.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#783]
## 기능에 관한 설명 또는 링크
기존의 모달의 스타일을 시안에 맞는 형태로 변경합니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
요구조건에 부합하는 형태로 스타일 적용

## 요구 조건
- [x] `variant`를 적용합니다.(`basic`, `layer`)
- [x] `type`을 적용합니다.(`basic` 인 경우만 동작, `alert`, `confirm`)
 - basic : close 버튼 x, type은 alert 확인만 존재하는 것과 confirm 확인과 취소가 존재하는 두 가지 형태
 - layer : 기존의 형태와 동일하나 buttons를 노출하지 않음.(버튼영역이 필요한 경우 children으로 전달하여 사용)
- [x] min-height: 232px;
- [x] modal 구성
 - title 영역: grey10, fs22
 - title description: grey08, fs14
 - contents: grey09, fs18
- [x] title, description, contents을 props으로 받도록 구현
- [x] basic인 경우 type에 따른 button의 onClick 이벤트를 전달받음.
 - onCancel(confirm의 취소), onConfirm(alert의 확인, confirm의 확인)

## 테스트 항목
- [x] 그려지는 모달을 확인한다.(styleguidist)

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요~!
