### ISSUE TITLE
[Modal] 미반영 스타일 적용.

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#789]
## 기능에 관한 설명 또는 링크
미반영된 스타일을 적용합니다.

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
아래 요구조건 반영

## 요구 조건
- [x] 콘텐츠 텍스트 : #grey10 으로 적용
- [x] x 아이콘은 포지션이 top:20px/right:20px 이어야 합니다.
- [x] 모달 액션버튼 크기는 large 사이즈 입니다.
`Basic Alert 과 Basic Confirm 버튼이 normal 사이즈로 적용되어 있습니다. large로 수정바랍니다.`

## 테스트 항목
- [x] 그려지는 항목 확인

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요
