### ISSUE TITLE
타입스크립트 변환 - Footer

### ISSUE THREAD

**Issue by jik0090** [linewalks/MDwalks-UI#791]
## 기능에 관한 설명 또는 링크
타입스크립트 변환 - Footer

## 선행 이슈 링크
있다면 링크의 URL 을 넣어 주세요

## 원하는 솔루션에 대한 설명
타입스크립트 적용

## 요구 조건
- [ ] 타입스크립트 변환 - Footer

## 테스트 항목
- 없음

## 완료 후 진행
PR 을 신청합니다

**Comment by thiporia** [comment]
진행요청드립니다. : )
