### ISSUE TITLE
[test] Timeline test 보완

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#816]
## 기능에 관한 설명 또는 링크
Timeline과 LineMergeTimeline의 테스트 보완

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
테스트 보완으로 커버리지가 향상되어야 합니다.

## 요구 조건
- [x] Timeline 테스트보완
~- [ ] LineMergeTimeline 테스트보완~

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요
