### ISSUE TITLE
[test] Pagination, TBody, THead 테스트 보완

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#825]
## 기능에 관한 설명 또는 링크
[test] Pagination, TBody, THead 테스트 보완

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
Pagination, TBody, THead 항목 테스트 커버리지 증가

## 요구 조건
- [v] Pagination 테스트 보완
~- [ ] TBody  테스트 보완~
~- [ ] THead  테스트 보완~

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요
