### ISSUE TITLE
[Docs] list 폴더 컴포넌트 정의서 작성

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#908]
## 기능에 관한 설명 또는 링크
[Docs] list 폴더 컴포넌트 정의서 작성

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
컴포넌트 정의서 양식에 따라 .md 파일 작성 후 docusaurus를 통해 확인할 수 있어야 합니다.

## 요구 조건
- [x] CheckBox
- [x] CheckList
- [x] Item
- [x] RadioList

## 테스트 항목
- 

## 완료 후 진행
PR 을 신청합니다

**Comment by jik0090** [comment]
진행해주세요
