### ISSUE TITLE
READMD.md 에 travis status 표현

### ISSUE THREAD

**Issue by toyjhlee** [linewalks/MDwalks-UI#909]
## 기능에 관한 설명 또는 링크
travis 의 [Embedding Status Images](https://docs.travis-ci.com/user/status-images/) 를 README.md 에 추가하면 좋을 듯 합니다.

## 요구 조건
- [ ]  README.md 에 travis status 표현

## 완료 후 진행
PR 을 신청합니다

**Comment by toyjhlee** [comment]
@thiporia @jik0090 진행 해도 될까요?

**Comment by thiporia** [comment]
@toyjhlee  진행요청드립니다. :)

**Comment by toyjhlee** [comment]
@thiporia @jik0090 push 권한이 없는 듯 합니다
